### PR TITLE
#5 added deployment file

### LINKED ISSUE #5: Setup Publishing to fhir/hl7.at
Setup the publishing process for PICA as IG

### PR DESCRIPTION
**Pull request by oliver-krauss**
Closes #5

### CODE REVIEW

**Comment by oliver-krauss** [comment]
@emuhell as soon as you slash fast-forward this will be on main

**Comment by oliver-krauss** [comment]
@pointan  I need someone to approve apparently

**Review by pointan — APPROVED** [review]

**Pull request merged**
